model:
  n_layer: 24
  vocab_size: 8724
  d_model: 768
  num_heads: 12

data:
  vocab_path: sohu_data/vocab.txt
  train_data_path: sohu_data/sohu_data_train.json
  val_data_path: sohu_data/sohu_data_valid.json

batch_size: 4
resume: False
epoch: 100
pretrained: pretrained
eval_epoch_interval: 1